# Generated by Django 5.0.6 on 2026-07-09 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'kopquest"."city',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False)),
                ('province_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'kopquest"."province',
            },
        ),
        migrations.CreateModel(
            name='Koperasi',
            fields=[
                ('koperasi_id', models.AutoField(primary_key=True, serialize=False)),
                ('koperasi_name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koperasi_list', to='accounts.city')),
            ],
            options={
                'db_table': 'kopquest"."koperasi',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='koperasi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='players', to='accounts.koperasi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='accounts.province'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('province', 'city_name'), name='uq_city_province_name'),
        ),
    ]
