# Generated by Django 5.0.6 on 2026-07-09 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_province_koperasi_player_koperasi_city_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='koperasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='accounts.koperasi'),
        ),
        migrations.RunSQL(
            sql='UPDATE "kopquest"."user" u SET koperasi_id = p.koperasi_id '
                'FROM "kopquest"."player" p WHERE p.user_id = u.user_id;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='player',
            name='koperasi',
        ),
    ]
