# Generated by Django 5.0.6 on 2026-07-09 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_number', models.PositiveIntegerField()),
                ('deadline_numberdays', models.PositiveIntegerField()),
                ('xp_reward', models.PositiveIntegerField()),
                ('gmv_target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='accounts.role')),
            ],
            options={
                'db_table': 'kopquest"."level',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('mission_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id_snapshot', models.BigIntegerField()),
                ('product_name_snapshot', models.CharField(max_length=150)),
                ('product_price_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_quantity', models.PositiveIntegerField()),
                ('target_gmv', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deadline_date', models.DateField()),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('failed', 'Failed')], default='ongoing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='missions', to='gamification.level')),
                ('player', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='accounts.player')),
            ],
            options={
                'db_table': 'kopquest"."mission',
            },
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('role', 'level_number'), name='uq_level_role_number'),
        ),
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ongoing')), fields=('player',), name='uq_mission_one_active_per_player'),
        ),
    ]
