# Generated by Django 5.0.6 on 2026-07-09 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_province_koperasi_player_koperasi_city_province_and_more'),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattlePassMilestone',
            fields=[
                ('milestone_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_xp_threshold', models.PositiveIntegerField(unique=True)),
                ('reward_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kopquest"."battle_pass_milestone',
            },
        ),
        migrations.CreateModel(
            name='PlayerBattlePassReward',
            fields=[
                ('reward_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reward_description_snapshot', models.CharField(max_length=255)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kopquest"."player_battle_pass_reward',
            },
        ),
        migrations.AddConstraint(
            model_name='battlepassmilestone',
            constraint=models.CheckConstraint(check=models.Q(('total_xp_threshold__gt', 0)), name='chk_milestone_threshold_positive'),
        ),
        migrations.AddField(
            model_name='playerbattlepassreward',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_rewards', to='gamification.battlepassmilestone'),
        ),
        migrations.AddField(
            model_name='playerbattlepassreward',
            name='player',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='battle_pass_rewards', to='accounts.player'),
        ),
        migrations.AddConstraint(
            model_name='playerbattlepassreward',
            constraint=models.UniqueConstraint(fields=('player', 'milestone'), name='uq_player_milestone'),
        ),
    ]
