# Generated by Django 5.0.6 on 2026-07-09 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_province_koperasi_player_koperasi_city_province_and_more'),
        ('gamification', '0002_battlepassmilestone_playerbattlepassreward_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mission',
            name='uq_mission_one_active_per_player',
        ),
        migrations.AddField(
            model_name='mission',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='missions', to='accounts.role'),
        ),
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ongoing')), fields=('player', 'role'), name='uq_mission_one_active_per_player_role'),
        ),
    ]
