# Generated by Django 5.0.6 on 2026-07-09 16:10

from django.db import migrations


def backfill_role(apps, schema_editor):
    Mission = apps.get_model('gamification', 'Mission')
    for mission in Mission.objects.filter(role__isnull=True).select_related('level'):
        mission.role_id = mission.level.role_id
        mission.save(update_fields=['role'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_mission_role_nullable'),
    ]

    operations = [
        migrations.RunPython(backfill_role, noop_reverse),
    ]
