# Generated by Django 5.0.6 on 2026-07-09 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_province_koperasi_player_koperasi_city_province_and_more'),
        ('gamification', '0004_backfill_mission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='missions', to='accounts.role'),
            preserve_default=False,
        ),
    ]
