# Generated by Django 5.0.6 on 2026-07-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_mission_role_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='referral_code',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
