# Generated by Django 5.0.6 on 2026-07-09 16:28

import random
import string

from django.db import migrations

ALPHABET = string.ascii_uppercase + string.digits


def backfill_codes(apps, schema_editor):
    Mission = apps.get_model('gamification', 'Mission')
    existing = set(Mission.objects.exclude(referral_code=None).values_list('referral_code', flat=True))
    for mission in Mission.objects.filter(referral_code=None):
        while True:
            code = "".join(random.choices(ALPHABET, k=5))
            if code not in existing:
                existing.add(code)
                break
        mission.referral_code = code
        mission.save(update_fields=['referral_code'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_mission_referral_code_nullable'),
    ]

    operations = [
        migrations.RunPython(backfill_codes, noop_reverse),
    ]
