# Generated by Django 5.0.6 on 2026-07-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_backfill_mission_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='referral_code',
            field=models.CharField(default=None, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
