# Generated by Django 5.0.6 on 2026-07-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_mission_referral_code_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='current_gmv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='mission',
            name='current_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
