# Generated by Django 5.0.6 on 2026-07-09 09:03

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cashier', models.ForeignKey(db_column='cashier_user_id', on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kopdes"."transaction',
            },
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_price')), output_field=models.DecimalField(decimal_places=2, max_digits=12))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transaction_details', to='catalog.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='transactions.transaction')),
            ],
            options={
                'db_table': 'kopdes"."transaction_detail',
            },
        ),
    ]
